sonar.projectKey=OneBusAway_maglev
sonar.organization=onebusaway
sonar.projectName=maglev
sonar.go.coverage.reportPaths=clean_profile.cov

# Ignore Sonar rule plsql:S1192 (String literals should not be duplicated) for SQL files 
# because sqlc requires inline strings for its arguments like sqlc.slice('slice_name')
sonar.issue.ignore.multicriteria=s1192
sonar.issue.ignore.multicriteria.s1192.ruleKey=plsql:S1192
sonar.issue.ignore.multicriteria.s1192.resourceKey=**/*.sql
